# Generated by Django 3.2.7 on 2021-09-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20210919_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Title',
            new_name='title',
        ),
    ]
