# Generated by Django 3.2.7 on 2021-09-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='book_images'),
        ),
    ]
