# Generated by Django 3.2.7 on 2021-09-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_auto_20210923_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
